-- Migration: pricing v3 — 3-tier hybrid (UTR + Razorpay).
-- Supersedes 20260822 pricing v2.
--
-- Changes:
--   1. quotations + payments tables (UTR bank-transfer flow)
--   2. subscriptions: plan_name + extra_data_points columns
--   3. get_entitlement() rewritten: 3-tier plans, 30-day trial, plan-based data points
--   4. Reset existing trials to 30 days from now
--
-- Pricing (source of truth):
--   Starter:  INR 999/mo  | 2697/qtr | 9990/yr  (2 data points)
--   Growth:   INR 2500/mo | 6750/qtr | 25500/yr (5 data points)
--   Pro:      INR 5000/mo | 13500/qtr| 50000/yr (10 data points)
--   Extra DP: Starter 299/249/199, Growth 499/399/299, Pro 799/649/499

-- ============================================================
-- 1. quotations (generated by the app, shared with client)
-- ============================================================
create table if not exists public.quotations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  quotation_number text unique not null,
  plan_name text not null,
  plan_term text not null,
  data_points integer not null,
  extra_data_points integer not null default 0,
  amount integer not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

alter table public.quotations enable row level security;

drop policy if exists "quotations_select_own" on public.quotations;
create policy "quotations_select_own" on public.quotations
  for select using (auth.uid() = user_id);

drop policy if exists "quotations_insert_own" on public.quotations;
create policy "quotations_insert_own" on public.quotations
  for insert to authenticated
  with check (auth.uid() = user_id);

create sequence if not exists public.quotation_seq start 1;

-- ============================================================
-- 2. payments (UTR bank-transfer verification log)
-- ============================================================
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  quotation_id uuid references public.quotations(id) on delete set null,
  utr_number text unique not null,
  amount_paid integer not null,
  plan_name text not null,
  plan_term text not null,
  data_points integer not null,
  extra_data_points integer not null default 0,
  bank_name text,
  auto_verified boolean not null default false,
  status text not null default 'verified',
  created_at timestamptz not null default now()
);

alter table public.payments enable row level security;

drop policy if exists "payments_select_own" on public.payments;
create policy "payments_select_own" on public.payments
  for select using (auth.uid() = user_id);

-- ============================================================
-- 3. subscriptions: add plan_name + extra_data_points columns
-- ============================================================
alter table public.subscriptions
  add column if not exists plan_name text not null default 'growth';

alter table public.subscriptions
  add column if not exists extra_data_points integer not null default 0;

-- ============================================================
-- 4. Reset all existing trials to 30 days from now
-- ============================================================
update public.profiles
  set trial_started_at = now()
  where trial_started_at is not null;

-- ============================================================
-- 5. get_entitlement() — rewritten for 3-tier plans
-- ============================================================
create or replace function public.get_entitlement()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_user_id uuid := auth.uid();
  v_email text := nullif(auth.jwt() ->> 'email', '');
  v_profile public.profiles%rowtype;
  v_sub public.subscriptions%rowtype;
  v_trial_end timestamptz;
  v_credit_end timestamptz;
  v_grace_end timestamptz;
  v_now timestamptz := now();
  v_sub_active boolean := false;
  v_dp_allowed int := 0;
  v_read_only boolean := false;
  v_trial_active boolean := false;
  v_credit_active boolean := false;
  v_in_grace boolean := false;
  v_extra_dp int := 0;
  v_plan_name text := 'growth';
  v_base_dp int := 5;
begin
  -- Demo account: unlimited access
  if v_email = 'demo@powerems.com' then
    return jsonb_build_object(
      'is_demo', true,
      'trial_end', null, 'trial_active', true,
      'subscription_status', 'active', 'sub_active', true,
      'free_months_credit', 0, 'credit_end', null, 'credit_active', false,
      'data_points_allowed', 999, 'extra_data_points', 0,
      'plan_name', 'pro', 'plan_term', 'yearly',
      'read_only', false, 'grace_end', null, 'in_grace', false,
      'referral_code', coalesce((select referral_code from public.profiles where user_id = v_user_id), ''),
      'current_period_end', null,
      'meters_allowed', 999, 'extra_meters', 0
    );
  end if;

  select * into v_profile from public.profiles where user_id = v_user_id;
  select * into v_sub from public.subscriptions where user_id = v_user_id;

  -- 30-day trial (was 60)
  v_trial_end := coalesce(v_profile.trial_started_at, v_now) + interval '30 days';
  v_trial_active := v_now < v_trial_end;
  v_credit_end := v_trial_end + (coalesce(v_profile.free_months_credit, 0) * interval '1 month');
  v_credit_active := v_now < v_credit_end;

  -- Subscription active check
  v_sub_active := coalesce(v_sub.status, 'none') in ('active', 'authenticated');
  v_extra_dp := coalesce(v_sub.extra_data_points, coalesce(v_sub.extra_meters, 0));
  v_plan_name := coalesce(v_sub.plan_name, 'growth');

  -- Map plan_name to base data points
  v_base_dp := case v_plan_name
    when 'starter' then 2
    when 'pro' then 10
    else 5
  end;

  if v_sub_active then
    v_dp_allowed := v_base_dp + v_extra_dp;
  elsif v_trial_active then
    -- During trial: starter plan gives 2 DP, others same as plan
    v_dp_allowed := v_base_dp + v_extra_dp;
  end if;

  -- During trial with no plan_name set, default to growth (5 DP)
  if v_trial_active and v_sub.plan_name is null then
    v_dp_allowed := 5;
    v_plan_name := 'growth';
  end if;

  v_read_only := not v_sub_active and not v_trial_active and not v_credit_active;

  -- Grace window
  if v_sub.current_period_end is not null then
    v_grace_end := v_sub.current_period_end + interval '7 days';
    v_in_grace := (v_now > v_sub.current_period_end)
      and (v_now < v_grace_end) and not v_sub_active;
  end if;

  return jsonb_build_object(
    'is_demo', false,
    'trial_end', v_trial_end, 'trial_active', v_trial_active,
    'subscription_status', coalesce(v_sub.status, 'none'), 'sub_active', v_sub_active,
    'free_months_credit', coalesce(v_profile.free_months_credit, 0),
    'credit_end', v_credit_end, 'credit_active', v_credit_active,
    'data_points_allowed', v_dp_allowed, 'extra_data_points', v_extra_dp,
    'plan_name', v_plan_name, 'plan_term', coalesce(v_sub.plan_term, 'monthly'),
    'read_only', v_read_only, 'grace_end', v_grace_end, 'in_grace', v_in_grace,
    'referral_code', coalesce(v_profile.referral_code, ''),
    'current_period_end', v_sub.current_period_end,
    'meters_allowed', v_dp_allowed, 'extra_meters', v_extra_dp
  );
end;
$$;

revoke execute on function public.get_entitlement() from public;
grant execute on function public.get_entitlement() to authenticated;

-- ============================================================
-- 6. RPC: verify a UTR payment (called by Edge Function via service_role)
-- ============================================================
create or replace function public.activate_utr_payment(
  p_user_id uuid,
  p_utr_number text,
  p_amount_paid integer,
  p_plan_name text,
  p_plan_term text,
  p_data_points integer,
  p_extra_data_points integer,
  p_bank_name text,
  p_auto_verified boolean
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_period_months int;
  v_period_end timestamptz;
begin
  -- Check duplicate UTR
  if exists (select 1 from public.payments where utr_number = p_utr_number) then
    return jsonb_build_object('verified', false, 'error', 'DUPLICATE_UTR');
  end if;

  -- Insert payment record
  insert into public.payments (
    user_id, utr_number, amount_paid, plan_name, plan_term,
    data_points, extra_data_points, bank_name, auto_verified, status
  ) values (
    p_user_id, p_utr_number, p_amount_paid, p_plan_name, p_plan_term,
    p_data_points, p_extra_data_points, p_bank_name, p_auto_verified,
    case when p_auto_verified then 'verified' else 'flagged' end
  );

  -- If auto-verified, activate the subscription
  if p_auto_verified then
    v_period_months := case p_plan_term
      when 'quarterly' then 3
      when 'yearly' then 12
      else 1
    end;

    v_period_end := now() + (v_period_months || ' months')::interval;

    insert into public.subscriptions (
      user_id, status, plan_name, plan_term, extra_data_points,
      base_amount, meter_rate,
      current_period_start, current_period_end,
      created_at, updated_at
    ) values (
      p_user_id, 'active', p_plan_name, p_plan_term, p_extra_data_points,
      0, 0,
      now(), v_period_end,
      now(), now()
    )
    on conflict (user_id) do update set
      status = 'active',
      plan_name = excluded.plan_name,
      plan_term = excluded.plan_term,
      extra_data_points = excluded.extra_data_points,
      current_period_start = now(),
      current_period_end = excluded.current_period_end,
      updated_at = now();
  end if;

  return jsonb_build_object(
    'verified', p_auto_verified,
    'plan_activated', p_auto_verified,
    'plan_name', p_plan_name,
    'plan_term', p_plan_term,
    'data_points', p_data_points + p_extra_data_points,
    'period_end', v_period_end
  );
end;
$$;

revoke execute on function public.activate_utr_payment(
  uuid, text, integer, text, text, integer, integer, text, boolean
) from public;
grant execute on function public.activate_utr_payment(
  uuid, text, integer, text, text, integer, integer, text, boolean
) to service_role;
